### ISSUE TITLE
Error in installing ("stnava/ANTsR")

### ISSUE THREAD

**Issue by taposh** [muschellij2/Neurohacking#3]
devtools::install_github("stnava/ANTsR")

1 warning generated.
cd /private/var/folders/46/zm1hrxpx0qxd1phxpr931fr40000gr/T/RtmpUgkg22/devtools1113a10bb7a42/stnava-ANTsR-69936eb/src/antb && make -j 2
make[1]: *** No targets specified and no makefile found.  Stop.
make: *** [libs] Error 2
ERROR: compilation failed for package ‘ANTsR’

**Comment by muschellij2** [comment]
Please put this as an issue on https://github.com/stnava/ANTsR
