### ISSUE TITLE
What image processing libraries in R are recommended for processing 2D nifti slices?

### ISSUE THREAD

**Issue by xuesongle** [muschellij2/Neurohacking#6]

**Comment by muschellij2** [comment]
In that case it is a matrix.  You can use all the matrix tools available,
but may want to look into ROpenCVLite, EBImage, magick packages for image
manipulation.


John

**Comment by xuesongle** [comment]
@muschellij2 , thanks for your reply. 


ROpenCVLite is a utility package that installs OpenCV within R for use by other packages. This package is not a wrapper around OpenCV (it does not provide access to OpenCV functions in R), not is it a computer vision package for R

The value of the sample nifti image is between [0,1133]. 

I tried with magick first with following testing code:
typeof(a)
[1] "integer"
> magick::image_display(a,animate = F)
Error in magick_image_display(image, animate) : 
  Expecting an external pointer: [type=integer].````
````

Then I tried with EBImage with the following code:
````
library("EBImage")
display(a, method="raster")
````
Then the resulting image is following
![test](https://user-images.githubusercontent.com/20032352/47690899-adb06580-dc3b-11e8-8034-f6a4048803d9.jpg)

Given pixel value in slice a is [0,1133], do I need to rescale it to 0 to 22 first? If so, does R has any normalized function for it?

Thanks.

**Comment by xuesongle** [comment]
![test](https://user-images.githubusercontent.com/20032352/47691149-b0f82100-dc3c-11e8-9a1a-bb588e8bed4c.jpg)

@muschellij2 , here is the proper link for the resulting image from EBImage library.

**Comment by muschellij2** [comment]
Ah - are you trying to plot?

You can use graphics::image(a, col = gray(0:64/64))

Also, you can also do:
library(oro.nifti)
image(nfImg, z = 11, plane = "axial")

or
oro.nifti::slice(nfImg, z = 11)

John

**Comment by xuesongle** [comment]
Thanks @muschellij2  No, I am intending to process each slice, such as viewing, smoothing, thresholding, and segmenting in 2D slice.

**Comment by xuesongle** [comment]
@muschellij2 , I tried to rescale a to range [0,255] as following:
````
b = rescale(a,to=c(0,255))
> min(b)
[1] 0
> max(b)
[1] 255
````
Result is still not good almost same as the 1st one.

**Comment by muschellij2** [comment]
"Result is still not good" - what does that mean?

viewing - viewing is plotting
smoothing - AnalyzeFMRI and kernsmooth R packages
thresholding - simply run img > threshold
segmenting - don't know what you want to segment - using watershed?  Gray
Matter vs. white matter?   Human vs. not human?

John

**Comment by xuesongle** [comment]
![test2](https://user-images.githubusercontent.com/20032352/47693812-d7bb5500-dc46-11e8-93ed-f7454d54823f.jpg)
Sorry, @muschellij2 This is the image b after rescaling from [0,1133] to [0,255] and display it using library("EBImage")
display(a, method="raster")

You are right, a lot of functions have been implemented in neuroconductor in 3D nifti doman. But there are more image processing functions in OpenCV and EbImage, such as instead of thresholding at a pre-calculated value. EBImage has otsu binary thresholding ( maximizes inter-class variance while minimize inner-class variance). My first step is to make sure that 2D slice extracted from nift image can be handled by other library proper, such as EBImage but seems there are some issues here. 

Thanks.

**Comment by xuesongle** [comment]
@muschellij2 , Hi, John. Another question here, is there a way I can write each nifti slice into a set of jpeg or png files in R ? 

Thanks.

**Comment by muschellij2** [comment]
png package:
https://www.rdocumentation.org/packages/png/versions/0.1-7/topics/writePNG

"My first step is to make sure that 2D slice extracted from nift image can
be handled by other library proper, such as EBImage but seems there are
some issues here." - yes I believe that is something you should do.

John

**Comment by xuesongle** [comment]
![b](https://user-images.githubusercontent.com/20032352/47761151-0f87d280-dd03-11e8-9ad8-693a836f7b71.png)
Result is above.

@muschellij2 Thanks for your valuable advice again. PNG does works better in converting each nifti slice to image in comparison to EBImage. 

I use PNG as a bridging tool between nifti slice and EBImage here. 

````
#get a slice and rescale value to 0 to 1 as 
a = nfImg[,,11]
b = rescale(a,to=c(0,1),from=c(min(a),max(a)))
library("png")
writePNG(b,target = "b.png")

library("EBImage")
c = readImage("b.png")
display(c,method = "browser")

````
Thanks again for your help!

**Comment by xuesongle** [comment]
@muschellij2 just had another go with EBImage and figured out the why did not work before. 

Same as PNG, the input image must be in range [0,1] instead of [0,255] I used yesterday.
So it works for EBImage without PNG library as well. 
````
a = nfImg[,,11]
b = rescale(a,to=c(0,1),from=c(min(a),max(a)))
display(b,method = "browser")
````
