### ISSUE TITLE
Issues in Registering ROI, Flair to T1 image

### ISSUE THREAD

**Issue by xuesongle** [muschellij2/Neurohacking#7]

**Comment by muschellij2** [comment]
One of the issues is that in `ants_regwrite`, you cannot specify another interpolator, so it uses the one for the original image (FLAIR), which will use a `Linear` interpolation.   I'd recommend using the `ants_regwrite` version 2 function, which is the `registration` function.  In `registration`, the argument `other_interpolator`, which allows you to pass through a different interpolator (`NearestNeighbor`).  Alternatively, you can use `ants_apply_transforms` on the ROI data separately, after the registration using `ants_regwrite`, to apply to the ROI with a `NearestNeighbor` interpolator.  I've changed the code below to reflect using `registration`.


```r
library(neurobase)
library(ANTsR)
library(extrantsr)
library(stringr)
library(fslr)

setwd("~/3D_Imaging/R_demo")

# read subject's T1, FLAIR, and ROI
mriPath <-"data/BRAINIX/NIfTI"
t1File <- file.path(mriPath,"T1.nii.gz")
t1 <- readnii(t1File,reorient = FALSE)
flairFile <- file.path(mriPath,"FLAIR.nii.gz")
flair <- readnii(flairFile)
roiFile <-file.path(mriPath,"ROI.nii.gz")
roi <- readnii(roiFile)
isTumorROI <- (roi>0)
roi[!isTumorROI] <- NA

orthographic(flair,roi, xyz=c(200,155,12),
             col.y=alpha("red",0.2),
             text="Image overlaid with mask",
             text.cex = 1.5)

#register flair, ROI to t1
reg_flairFile = file.path(mriPath,"FLAIR_regToT1.nii.gz")
reg_roiFile = file.path(mriPath,"ROI_regToT1.nii.gz")
reg_flair_list = registration(filename = flairFile,
                              template.file = t1File,
                              outfile = reg_flairFile,
                              typeofTransform = "Rigid",
                              other.files = roiFile,
                              other_interpolator = "NearestNeighbor", 
                              other.outfiles = reg_roiFile,
                              verbose = FALSE)
reg_roi = readNIfTI(reg_roiFile, reorient = FALSE)

double_ortho(t1,reg_flair_list$outfile)

ortho2(reg_flair$outfile,reg_roi,col.y=alpha("red",0.2))
```

**Comment by xuesongle** [comment]
@muschellij2 , John. Thanks for your reply. The modified code double_ortho(t1,reg_flair) does not work due to registration function actually returns a list instead of nifit object. 
After adding a line to read registered flair image, reg_flair = readnii(reg_flairFile,reorient = FALSE) code continues to execute.
But the final result still shows no mask in sagittal view. To check provided ROI input is correct, so I use ortho2(flair,roi,col.y=alpha("red",0.2)) and find no mask in sagital view either. So my suspicion is whether provided input ROI mask is correctly draw or not.  

result after ortho2(flair,roi,col.y=alpha("red",0.2)) 
![image](https://user-images.githubusercontent.com/20032352/51213726-72ceeb80-1967-11e9-893e-61c91359d000.png)
result after ortho2(reg_flair,reg_roi,col.y=alpha("red",0.2))
 
![image](https://user-images.githubusercontent.com/20032352/51213769-93974100-1967-11e9-9685-0e2f394ccc0c.png)

**Comment by muschellij2** [comment]
I'm not sure what you mean "no mask in sagittal view either" - all the images you've shown has a pink/red color overlaid on the image.

**Comment by xuesongle** [comment]
@muschellij2 , sorry I could not find the pink/red color overlaid on the sagittal view here or 2nd image in each graph.

**Comment by muschellij2** [comment]
![tmp](https://user-images.githubusercontent.com/1075118/51215680-c00f7680-18ef-11e9-86f9-9c1b41670f17.png)

I'm saying the ROI is there from the above image.  If you want to see the roi in the `ortho2`, you need to change `xyz` argument.

Try `ortho2(reg_flair,reg_roi,col.y=alpha("red",0.2), xyz = xyz(reg_roi))` and let me know if that works

**Comment by muschellij2** [comment]
Default is the middle of the image.  If you want to change where the image
crosshairs are, you need to set xyz.
John

**Comment by xuesongle** [comment]
Thanks, @muschellij2
