### ISSUE TITLE
How to label a registered image given an atlas image?

### ISSUE THREAD

**Issue by xuesongle** [muschellij2/Neurohacking#8]

**Comment by muschellij2** [comment]
Did you use `template.file = "JHU_MNI_SS_T1_brain.nii.gz"`?

**Comment by xuesongle** [comment]
Yes, I did use it
````
#step 2: register t1 to template t1 brain-stripped space 
templatePath <-"data/Eve_Atlas-master"
templateT1File <-file.path(templatePath,"JHU_MNI_SS_T1_brain.nii.gz")
templateT1 <- readnii(templateT1File)
...
#step 2.2 register t1, roiReg2T1File, to template T1 space
regT12TemplateT1<- ants_regwrite(filename = bet2_T1,template.file = templateT1File,
                                 outfile = t12TemplateFile,
                                 other.files = roiReg2T1File,
                                 other.outfiles = roi2TemplateFile,
                                 verbose = FALSE,
                                 typeofTransform = "SyN"
)
````

**Comment by muschellij2** [comment]
The file `T1_reg2_Eve.nii.gz` is **now in the Eve space**.  You can use the labels from Eve (assuming a good registration) that these labels are applicable to your scan.  If you want them in native space , you need to do the reverse registration.

**Comment by xuesongle** [comment]
@muschellij2 , Hi, John:

I am still not every clear about how I can apply labels from  T1_reg2_Eve.nii.gz to my scan here.
T1_reg2_Eve.nii.gz is now in the Eve space.
But I doubt if the labels from Eve can be applicable to T1_reg2_Eve.nii.gz without generating a warped labels first.
For example if a voxel v at position (50,50,50) in eve atlas is labelled as 1, the registered image  T1_reg2_Eve.nii.gz may not have the same label 1 at the same position (50,50,50) due to transformation. 
This is after registeration, voxel v (50,50,50) in eve atlas may be mapped to another position such as (51,51,51) in the registered image  T1_reg2_Eve.nii.gz, so the labels at the same position (50,50,50) may not be the same.

The only way I can think of direct application of Eve labels to registered image T1_reg2_Eve.nii.gz is that assumption voxels in both Eve label and registered image T1_reg2_Eve.nii.gz are identical so it is safe to apply labels from Eve to T1_reg2_Eve.nii.gz. 

Is my understanding correct here, thanks?

**Comment by muschellij2** [comment]
Yes.  So either you believe the data is in the same space and matches well
or you don't.  If you don't, then you need to perform additional
registration.  If you do, then the labels **should** be the same as the
spaces match up.  Therefore the eve labels apply to your data (with no
warping).

Again, if you want to transform the Eve labels to the image space (you've
done the other way around), you need to reverse the transformation, but
making sure you do a nearestneighbor or genericLabel interpolation and not
linear (as these are labels).

**Comment by xuesongle** [comment]
@muschellij2 , thank, John.

I will have go on "transform the Eve labels to the image space". Before I head into it. Would you kindly explain the usage of "atlas.file = NULL" parameters in ants_regwrite function?
````
ants_regwrite(filename, skull_strip = FALSE, correct = FALSE,
correction = "N3", retimg = TRUE, outfile = NULL,
template.file = file.path(fsldir(), "data", "standard",
"MNI152_T1_1mm_brain.nii.gz"), interpolator = "Linear",
other.files = NULL, other.outfiles = NULL, native.cereb = FALSE,
native.fname = NULL, atlas.file = NULL, typeofTransform = "SyN",
remove.warp = TRUE, outprefix = NULL, bet.opts = "-B -f 0.1 -v",
betcmd = "bet", verbose = TRUE, reproducible = TRUE, seed = 1,
...)
````
Thanks.

**Comment by xuesongle** [comment]
@muschellij2 , Hi, John:
Here is the code for transform labels from Eve back to subject's brain-extracted T1 weighted image bet2_T1, 
````
altasFile <- file.path(templatePath,"JHU_MNI_SS_WMPM_Type-I.nii.gz")
altasImg <- readnii(altasFile,reorient = FALSE)
template2t1File <-file.path(regPath,"Eve_reg2_t1.nii.gz")
regTemplate2T1<- ants_regwrite(filename = altasImg, 
                               template.file = bet2_T1,
                              outfile = template2t1File,
                               interpolator = genericlabel,
                               verbose = FALSE,
                               typeofTransform = "SyN")

````
Q1 Will template2t1File store warped labels are registration?
Q2: One concern that I have here is that data in altasImg are labels while data in bet2_T1 are actual voxel values from MRI, will it affect the result of registered labels?
Q3: After running code, the following error generated: Error in substring(interpolator[1], 1, 1) : 
  object 'genericlabel' not found
Thanks.

**Comment by muschellij2** [comment]
```r
library(extrantsr)
#step 2: register template to t1 brain-stripped space 
templatePath <-"data/Eve_Atlas-master"
templateT1File <- file.path(templatePath,"JHU_MNI_SS_T1_brain.nii.gz")
altasFile <- file.path(templatePath, "JHU_MNI_SS_WMPM_Type-I.nii.gz")
template2t1File <- file.path(regPath, "Eve_reg2_t1.nii.gz")
label_outfile <- file.path(regPath, "Eve_labels_reg2_t1.nii.gz")

regTemplate2T1 <- registration(
  filename = templateT1File,
  template.file = bet2_T1,
  outfile = template2t1File,
  other.files = altasFile,
  other.outfiles = label_outfile,
  other_interpolator = "NearestNeighbor",
  interpolator = genericlabel,
  verbose = FALSE,
  typeofTransform = "SyN"
)
```

**Comment by xuesongle** [comment]
@muschellij2 , Hi, John. Thanks, this code makes more sense now. I will have go and let you know the result.

**Comment by xuesongle** [comment]
@muschellij2 , still not working. 

````
> regTemplate2T1 <- registration(
+   filename = templateT1File,
+   template.file = bet2_T1,
+   outfile = template2t1File,
+   other.files = altasFile,
+   other.outfiles = label_outfile,
+   other_interpolator = "NearestNeighbor",
+   interpolator = genericlabel,
+   verbose = FALSE,
+   typeofTransform = "SyN"
+ )
Error in substring(interpolator[1], 1, 1) : 
  object 'genericlabel' not found
````
Here is the bet2_T1 image file 
[bet2_T1.nii.gz](https://github.com/muschellij2/Neurohacking/files/2959294/bet2_T1.nii.gz)

**Comment by xuesongle** [comment]
@muschellij2 , HI, John. After I change it to  interpolator = "genericLabel, it works.

**Comment by xuesongle** [comment]
@muschellij2 , Hi, John. That's for your great help. The only trivial thing I notice is that warped labels in label_outfile is stored as double instead of integer as in altasFile.  Is there any way to convert the data type from one to the other for niffti file in R?

**Comment by muschellij2** [comment]
See neurobase::datatyper.
John

**Comment by xuesongle** [comment]
@muschellij2 , Dear John:

I have 2 questions about the data conversion in this case.
Q1: different results between print and typeof ?
Given 2 nifiti images, using print function gives same data type for each of them
````
template2T1_read <- readnii(label_outfile,reorient = FALSE)
atlas_read <- readnii(altasFile,reorient = FALSE)
> print(template2T1_read)
NIfTI-1 format
  Type            : nifti
  Data Type       : 4 (INT16)
  Bits per Pixel  : 16
  Slice Code      : 0 (Unknown)
  Intent Code     : 0 (None)
  Qform Code      : 1 (Scanner_Anat)
  Sform Code      : 0 (Unknown)
  Dimension       : 512 x 512 x 22
  Pixel Dimension : 0.47 x 0.47 x 6
  Voxel Units     : mm
  Time Units      : Unknown
> print(atlas_read)
NIfTI-1 format
  Type            : nifti
  Data Type       : 4 (INT16)
  Bits per Pixel  : 16
  Slice Code      : 0 (Unknown)
  Intent Code     : 0 (None)
  Qform Code      : 2 (Aligned_Anat)
  Sform Code      : 1 (Scanner_Anat)
  Dimension       : 181 x 217 x 181
  Pixel Dimension : 1 x 1 x 1
  Voxel Units     : mm
  Time Units      : Unknown
````
but the typeof function shows different result
````
> typeof(template2T1_read)
[1] "double"
> typeof(atlas_read)
[1] "integer
````
Do you know why the data type is different when typeof function is used?

Q2 I attempted to use datatyper function to convert template2T1_read to  integer type "DT_UINT16", it seems I used the wrong value for argument type_string, would you give me some examples about using datatyper function?
````
> ta <- datatyper(img=template2T1_read,type_string = "DT_UINT16")
Error: type_string %in% accepted is not TRUE
````
Thanks.

**Comment by muschellij2** [comment]
Please see ?oro.nifti::convert.bitpix
John

**Comment by xuesongle** [comment]
@muschellij2 , Thanks for the tip, John:
pct3 = datatyper(template2T1_read, type_string = convert.datatype(4),convert.bitpix(16))
does make it work. However, the typeof(pct3) still shows double instead of integer
> typeof(pct3)
[1] "double"
> typeof(atlas_read)
[1] "integer"
Why it is different? Is there any to change it to integer as well?

**Comment by jninneman** [comment]
I'm thinking this might be an applicable thread to post my question as I haven't really been able to find anywhere else this fits. I'm doing a VBM analysis with a template derived from the sample population. I wanted to use the Harvard-oxford atlas to label regions in the new template space. I'm assuming the code you presented above would tackle this issue with inputs of my template and of the harvard atlas. If my question doesn't fit here and there are better spots please feel free to embarrass me. thanks!

**Comment by muschellij2** [comment]
I think when using a subject-specific template you need to be very careful
carrying over labels.  The spaces can be quite different.   You could
register MNI to the sample population, but the registration may not be good
enough for great overlap with the atlas.  You can do the sample population
in MNI space, but the same morphological issues arise as the registration
procedure.  You can also estimate the labels in each person and then do a
label fusion on the population, which may be better.
Best,
John

**Comment by jninneman** [comment]
Thanks for the really quick reply John. I do take heed of the shortcomings of my route but would prefer to do analyses in the study sample space in lieu of MNI space. When you say estimating labels, are you meaning the warping of Harvard-oxford labels to each individual (which has been registered to template space) and then fusing them? I am unsure of how to complete both of these steps. Thanks again!
Jacob

**Comment by muschellij2** [comment]
If they are all in MNI space and labeld with Harvard/Oxford, why do you need the labels again?
If the template is in MNI space, you could warp the labels from the MNI template, but given above caveats.
It depends on your purpose.

As this repo is for neurohacking and not general questions, I will leave this as closed and close responses accordingly.
